### ISSUE TITLE
NoMethodError: No resource or method named `action_install' for `Chef::Provider::GitClient'

### ISSUE THREAD

**Issue by kbaltrinic** [jssjr/git#57]
Not sure if this needs to be fixed but we are getting this error with the new 4.2 version of the git cookbook when running on older versions of the chef client (v 11.18.x).  Workaround that we tests are to downgrade to git 4.1 or upgrade the chef client. (Both work, we when with upgrading chef to 12.0.3).  

<pre>
NoMethodError: git_client[default] (git::default line 19) had an error: NoMethodError: No resource or method named `action_install' for `Chef::Provider::GitClient ""'

/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/dsl/recipe.rb:46:in `rescue in method_missing'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/dsl/recipe.rb:43:in `method_missing'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/provider.rb:121:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource.rb:648:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/resource_collection.rb:96:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/client.rb:345:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/client.rb:431:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/client.rb:213:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/client.rb:207:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/client.rb:207:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/application/client.rb:338:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/application/client.rb:327:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/application/client.rb:327:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/lib/chef/application.rb:55:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:23:in `load'
/usr/bin/chef-client:23:in `<main>'
</pre>

**Comment by Ghjnut** [comment]
Same thing here. Pinning to 4.1.0 fixes.

**Comment by someara** [comment]
investigating

**Comment by Ghjnut** [comment]
Mostly same info, but here's my kitchen backtrace
```
       Recipe: git::default
       
           
           ================================================================================
           Error executing action `install` on resource 'git_client[default]'
           ================================================================================
           
           NoMethodError
           -------------
           No resource or method named `action_install' for `Chef::Provider::GitClient ""'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/git/recipes/default.rb
           
            19: git_client 'default' do
            20:   action :install
            21: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/git/recipes/default.rb:19:in `from_file'
           
           git_client("default") do
             action [:install]
             retries 0
             retry_delay 2
             guard_interpreter :default
             cookbook_name "git"
             recipe_name "default"
           end

**Comment by nickma** [comment]
4.2.0 Doesn't seem to be backwards compatible. 
Error executing action `install` on resource 'git_client[default]'

Pinned it to 4.1.0

**Comment by someara** [comment]
This is fixed up in 4.2.1. Sorry for the hiccup!

**Comment by someara** [comment]
Fixed with c2b63fef27d667e11af4d1ee05e2055dd3822291

**Comment by Ghjnut** [comment]
Thanks! :+1:

**Comment by pelletiermaxime** [comment]
Had the same problem today with a rapberry-pi that has chef-client 11.18.6.
Pinning to 4.1.0 fixed it for now.

**Comment by JimFluke** [comment]
I had the same problem today with a Windows 7 VM and chef-client 11.16.4.
Pinning to 4.1.0 fixed it.

**Comment by martinmosegaard** [comment]
I saw this on OSX today, also with v4.1.0 of the git cookbook.

**Comment by iennae** [comment]
@martinmosegaard it's not clear whether you are still having this issue. This issue has been marked as closed. If you are still having this problem, please open a new issue and fill out the issue template. Thanks.
