### ISSUE TITLE
Git is building from source instead of from package

### ISSUE THREAD

**Issue by BackSlasher** [jssjr/git#71]
Not sure why, but version `4.2.2` installs git from package on our CentOS servers (as desired), but upgrading to latest version causes git to be compiled from source.  
A lot of cookbooks rely on this one (by calling `include_recipe 'git'`), and I can't seem to find a way to instruct installation from package, since both providers... provide with the same configuration

**Comment by someara** [comment]
Hi. Just fixed this up in 4.2.4

**Comment by BackSlasher** [comment]
Thanks for the quick response!
Just out of curiosity, how does one trigger source builds now?

**Comment by someara** [comment]
Like this:
https://github.com/jssjr/git/blob/9e872051f06fff03d6c6dae3c95675f1ef58cba1/recipes/source.rb#L21

-s

**Comment by BackSlasher** [comment]
You might want to make it a node attribute, like `node['git']['source']`, but don't wanna impose.
Thanks again!

**Comment by BackSlasher** [comment]
Are you releasing version 4.2.4 to supermarket?

**Comment by someara** [comment]
There's a 4.2.4 on supermarket.... we're are 4.3.1 now
-s

**Comment by BackSlasher** [comment]
Sorry, thanks!
