### ISSUE TITLE
git submodules are not downloaded with git resource

### ISSUE THREAD

**Issue by puneetloya** [jssjr/git#83]
git tests_dir do
  repository node['xyz']['repo']
  revision node['xyz']['branch']
  enable_submodules true
  action :sync
end

It is downloading the main parent repository but not the submodules. I am getting only the .gitmodules file and nothing else. Am I missing something very basic?

**Comment by someara** [comment]
Hello! The "git" resource ships in Core Chef, not this cookbook. Can you please file this at github.com/chef/chef ?

**Comment by puneetloya** [comment]
This issue was moved to chef/chef#4126
